export const CHANGE_ALL_RANKING = "ranking/CHANGE_ALL_RANKING";
export const CHANGE_CURRENT_RANKING = "ranking/CHANGE_CURRENT_RANKING";
export const CHANGE_RANKING_COMMENT = "ranking/CHANGE_RANKING_COMMENT"